(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".demo-btn"),o=document.getElementById("gameIframe"),s=document.getElementById("closeIframeBtn");r&&o&&s&&(r.addEventListener("click",n=>{n.preventDefault();const e=r.getAttribute("data-game-url");o.src=e,o.style.display="block",s.style.display="flex"}),s.addEventListener("click",()=>{o.style.display="none",s.style.display="none",o.src=""}))});document.addEventListener("DOMContentLoaded",function(){const r=document.getElementById("cookie-popup"),o=document.getElementById("accept-cookies"),s=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(r.style.display="block"),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),r.style.display="none"}),s.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),r.style.display="none"})});document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".menu-button"),o=r.querySelector(".icon"),s=document.querySelector(".modal"),n=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const c=`
 <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5 7H23" stroke="#FFCC5A" stroke-width="3" stroke-linecap="round" />
  <path d="M5 14H23" stroke="#FFCC5A" stroke-width="3" stroke-linecap="round" />
  <path d="M5 21H23" stroke="#FFCC5A" stroke-width="3" stroke-linecap="round" />
</svg>
    `,i=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M8 20L20.7279 7.27208" stroke="#FFCC5A" stroke-width="3" stroke-linecap="round" />
  <path d="M8 7L20.7279 19.7279" stroke="#FFCC5A" stroke-width="3" stroke-linecap="round" />
</svg>
    `;r.addEventListener("click",()=>{t=!t,o.innerHTML=t?i:c,t?d():l()}),n.forEach(u=>u.addEventListener("click",()=>{l(),o.innerHTML=c,t=!1})),window.addEventListener("scroll",a);function d(){s.style.display="block"}function l(){s.style.display="none"}function a(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function r(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const e=document.getElementById(n);if(!e)return;const t=r(),c=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:c,behavior:"smooth"})}document.querySelectorAll('a[href*="#"]').forEach(n=>{n.addEventListener("click",function(e){const t=this.getAttribute("href"),c=t.indexOf("#");if(c===-1)return;const i=t.substring(c+1);!t.startsWith("http")&&(t.startsWith("#")||t.startsWith("index.html#"))&&(e.preventDefault(),o(i))})});const s=window.location.hash;if(s){const n=s.substring(1);setTimeout(()=>{o(n)},1e3)}});
//# sourceMappingURL=index.js.map
